### ISSUE TITLE
Task 3ca: Edit Story - Bugs/ToDo

### ISSUE THREAD

**Issue by angMaidt** [angMaidt/Screamium#10]
- [x] When redirecting to story page, there is a moment where you can see the old info
- [x] Need a cancel edit button
- [x] Note, ended up restructuring to a dynamic update
- [x] User must hit cancel edit in order to edit the story again
