### ISSUE TITLE
Task 3ba: Create Story - Bugs/Todo

### ISSUE THREAD

**Issue by angMaidt** [angMaidt/Screamium#15]
- [x] If you don't navigate to `/stories/:storyId` from `/stories`, the story won't show
- [x] `/stories` should only render a preview of a story
- [x] Reloading on `/stories/:storyId` breaks the page, need to conidtionally render and hydrate
- [x] Story Validators - backend and frontend
- [x] Should redirect to new story page after creation
